name: gamble-coin

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    user: node
    environment:
      - NODE_ENV=production
      - PORT=80
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - backend
    command: ["node","--env-file=.env", "build/index.js"]

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gamble-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db_data: